/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

/**
 *
 * @author Anushka
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cel2fah = new javax.swing.JButton();
        fah2cel = new javax.swing.JButton();
        close = new javax.swing.JButton();
        inch2centi = new javax.swing.JButton();
        centi2inch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dol2rup = new javax.swing.JButton();
        rup2dol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cel2fah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cel2fah.setText("Celsius to Fahrenheit");
        cel2fah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cel2fahActionPerformed(evt);
            }
        });

        fah2cel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fah2cel.setText("Fahrenheit to Celsius");
        fah2cel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fah2celActionPerformed(evt);
            }
        });

        close.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        inch2centi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        inch2centi.setText("Inch to Centimeter");
        inch2centi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inch2centiActionPerformed(evt);
            }
        });

        centi2inch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        centi2inch.setText("Centimeter to Inch");
        centi2inch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centi2inchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Unite Converter");

        dol2rup.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dol2rup.setText("Dollar to Rupee");
        dol2rup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dol2rupActionPerformed(evt);
            }
        });

        rup2dol.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rup2dol.setText("Rupee to Dollar");
        rup2dol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rup2dolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(centi2inch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cel2fah, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(fah2cel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(close, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inch2centi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dol2rup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rup2dol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rup2dol, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dol2rup, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cel2fah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fah2cel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inch2centi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(centi2inch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cel2fahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cel2fahActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Cel2Fah().setVisible(true);
    }//GEN-LAST:event_cel2fahActionPerformed

    private void fah2celActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fah2celActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Fah2Cel().setVisible(true);
    }//GEN-LAST:event_fah2celActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dispose();
        //MainWindow.dispatchEvent(new WindowEvent(MainWindow, WindowEvent.WINDOW_CLOSING));
        System.exit(0); 
    }//GEN-LAST:event_closeActionPerformed

    private void inch2centiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inch2centiActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Inch2Centi().setVisible(true);
    }//GEN-LAST:event_inch2centiActionPerformed

    private void centi2inchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centi2inchActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Centi2Inch().setVisible(true);
    }//GEN-LAST:event_centi2inchActionPerformed

    private void dol2rupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dol2rupActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Dollar2Rupee().setVisible(true);
    }//GEN-LAST:event_dol2rupActionPerformed

    private void rup2dolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rup2dolActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new RupeetoDollar().setVisible(true);
    }//GEN-LAST:event_rup2dolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cel2fah;
    private javax.swing.JButton centi2inch;
    private javax.swing.JButton close;
    private javax.swing.JButton dol2rup;
    private javax.swing.JButton fah2cel;
    private javax.swing.JButton inch2centi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton rup2dol;
    // End of variables declaration//GEN-END:variables
}
